server: 
  port: 8011
spring:
  profiles: dev #开发环境
  application:
    name: config_client_dev
eureka:
  client:
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
---  
#---表示分区块
server: 
  port: 8011
spring:
  profiles: test #测试环境
  application:
    name: config_client
eureka:
  client:
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
